# Collector specific configuration
base_url: "https://data.unhcr.org/population/get/origin"

dataset_name: "unhcr-situations"
dataset_title: "UNHCR Situations: Monthly Refugees and Asylum Seekers"
tags:
  - "asylum seekers"
  - "refugees"

geo_ids:
  - "589"
  - "594"
  - "349"
  - "399"
  - "410"
  - "509"
  - "535"
  - "633"
  - "637"
  - "639"
  - "643"
  - "684"
  - "697"
  - "699"
  - "723"
  - "726"
  - "745"
  - "587"
  - "160"
  - "178"
  - "719"
  - "192"
  - "259"
  - "295"
  - "217"
  - "220"
  - "151"
  - "578"
  - "486"
  - "686"
  - "689"
  - "761"
  - "762"

population_collections:
  - "4"
  - "29"
