package_creator: "briar-mills"
dataset_source: "UNHCR"
data_update_frequency: "30"
license_id: "cc-by-igo"
caveats: "The frequency for some countries may not be monthly"
subnational: "0"
methodology: "Other"
methodology_other: "The collection, compilation, quality assurance and dissemination of statistics on refugees, asylum-seekers, internally displaced persons (IDPs) and stateless people is challenging. Statistics are collated primarily from governments hosting these populations, UNHCR's own registration data and more rarely data published by non-governmental organizations."
private: False
notes: "Refugees and Asylum-seekers in Southern Africa, East and Horn of Africa and the Great Lakes Region as a result of persecution, conflict, violence, human rights violations, or events seriously disturbing public order."
